#%RAML 1.0 NamedExample

 Workers:
  - First_Name: John  
    Last_Name: Sparten  
    Email: jhon_sparten@caloes.ca.go  
    Work_Phone: 916-885-7789  
    Job_Title: Demolition Man  
    Supervisory_Org: No Org  
    Office_Location: Building D  
  - First_Name: John  
    Last_Name: Sparten  
    Email: jhon_sparten@caloes.ca.go  
    Work_Phone: 916-885-7789  
    Job_Title: Demolition Man  
    Supervisory_Org: No Org  
    Office_Location: Building D